{%- set project_slug = cookiecutter.project_slug|lower|replace(' ','_')|replace('-','_') -%}
site_name: {{ cookiecutter.project_name }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ project_slug }}
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - nl2br
    - codehilite
    - sane_lists
